download_limit_mb: 10
targets: ["github"]

sources: 
  kaggle: 
      max_session_downloads: 10
      credentials_file: "/Users/guycutting/.kaggle/kaggle.json"
  openml:
      max_session_downloads: 10
  datahub: 
      - max_session_downloads: 3
      - credentials_file: "/Users/guycutting/.kaggle/kaggle.json"
  quandl: 
      - max_session_downloads: 3
      - credentials_file: "/Users/guycutting/.kaggle/kaggle.json"
  worldbank: 
      - max_session_downloads: 3
      - credentials_file: "/Users/guycutting/.kaggle/kaggle.json"