download_limit_mb: 10
targets: ["github"]

# need to decide on initial list of sources
# find the ones (like kaggle) that both have a lot of datasets and have a relatively easy-to-implement api
sources: 
  kaggle: 
      max_session_downloads: 10
      credentials_file: "/Users/guycutting/.kaggle/kaggle.json"
  openml:
      max_session_downloads: 10
  datahub: 
      - max_session_downloads: 3
      - credentials_file: "/Users/guycutting/.kaggle/kaggle.json"
  quandl: 
      - max_session_downloads: 3
      - credentials_file: "/Users/guycutting/.kaggle/kaggle.json"
  worldbank: 
      - max_session_downloads: 3
      - credentials_file: "/Users/guycutting/.kaggle/kaggle.json"